### PR TITLE
Allow Mounting of Apps

### PR DESCRIPTION
**Pull request by shadowtime2000**
**Please describe the changes this PR makes and why it should be merged:**

This allows you to choose specific parts of the DOM to use for Lucia component scopes.

**Status**

- [x] Code changes have been tested against eslint, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
I'm not sure how to commit to this PR as well, but here's my code for latest comment on the 2313b28 commit

```js
import VDom from './vdom';
import compute from './helpers/compute';
import directives from './directives';
import observer from './observer';

export { compute, directives, observer };

export class App extends VDom {
  constructor(options: Record<string, unknown>) {
    super(options || {});
  }
}

export const createApp = (view: Record<string, unknown>) => {
  return new App(view);
};

export const use = (name: string, view: Record<string, unknown>): App | void => {
  const elements = Array.from(document.querySelectorAll('[l-use]'));

  for (const el of elements) {
    const component = el.getAttribute('l-use');

    if (component === name) {
      const app = createApp(view);
      app.mount(el);

      return app;
    }
  }
};

export const init = (directive = 'use') => {
  const elements = Array.from(document.querySelectorAll(`[l-${directive}]`));

  for (const el of elements) {
    const view = el.getAttribute(`l-${directive}`);
    if (view === null) return;

    try {
      const app = createApp(compute(view));
      app.mount(el);
    } catch (err) {}
  }
}

document.addEventListener('DOMContentLoaded', () => init('init'));
```

```md
| Directive                                                           | Description                                                                             |
| ------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| [`l-use`](https://lucia.js.org/docs/features/)                      | Declares a new component scope.                                                         |
| [`l-init`](https://lucia.js.org/docs/features/)                     | Declares and automatically initializes a new component scope.                           |
| [`l-text`](https://lucia.js.org/docs/features/declarativeRendering) | Works similarly to `l-bind`, but will update the `textContent` of an element.           |
| [`l-html`](https://lucia.js.org/docs/features/declarativeRendering) | Works similarly to `l-bind`, but will update the `innerHTML` of an element.             |
| [`l-if`](https://lucia.js.org/docs/features/conditionals)           | Toggles `display: none;` on the element depending on expression (true or false).        |
| [`l-on`](https://lucia.js.org/docs/features/eventHandling)          | Attaches an event listener to the element. Executes JavaScript expression when emitted. |
| [`l-bind`](https://lucia.js.org/docs/features/attributeBinding)     | Sets the value of an attribute to the result of a JavaScript expression.                |
| [`l-join`](https://lucia.js.org/docs/features/joiningItems)         | Create new DOM nodes for each item in an array.                                         |
| [`l-model`](https://lucia.js.org/docs/features/formInputBindings)   | Adds "two-way data binding" to an element. Keeps input element in sync with view data.  |
```

**Comment by shadowtime2000** [comment]
@aidenybai I am a little confused by what you are trying to say. Can you clarify?

**Comment by aidenybai** [comment]
This is to maintain the "simple" example that doesn't need javascript but also allow for external initialization

**Comment by shadowtime2000** [comment]
I think we should allow users to specify what element to use as the "root" for the `querySelectorAll`.

**Comment by aidenybai** [comment]
Sounds like a good idea, just edited my comment to reflect that

**Comment by shadowtime2000** [comment]
Ok, your code seems a little better so I am going to close this PR. @aidenybai You should probably commit those changes to `master` and I will update the documentation when I can. We should probably wait for the `vdom-refactor` branch merge into `master` to pile major/breaking changes together before publishing.

**Comment by aidenybai** [comment]
Sounds good. Just pushed changes

**Pull request closed without merging**
